<!DOCTYPE html>
<html>
    <head>
        <title>MVC Test</title>
    </head>

    <body>

        <h1>{{ Title }}</h1>

        {{ Layout }}

        <p>Generated by mvc test</p>
    </body>

</html>

